# Generated by Django 2.1.4 on 2019-01-06 18:05

from django.db import migrations, models
import uuid
import secrets


def add_values(apps, schema_editor):
    """
    Pre-set configuration values
    """
    Configuration = apps.get_model("configuration", "Configuration")
    db_alias = schema_editor.connection.alias

    system_secret = secrets.token_hex(16)

    config = Configuration.objects.using(db_alias).first()
    if not config:
        # Create values row
        config = Configuration(system_secret=system_secret)
        config.save()
    else:
        # Update values row
        config.system_secret = system_secret
        config.save()


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('system_secret', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(add_values)
    ]
