# Generated by Django 2.0.6 on 2018-07-01 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access_points', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesspoint',
            options={'permissions': (('allowed_access', 'Allowed access'),)},
        ),
    ]
